# Generated by Django 5.2.8 on 2025-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("src_ip", models.CharField(max_length=100)),
                ("src_port", models.IntegerField()),
                ("dst_ip", models.CharField(max_length=100)),
                ("dst_port", models.IntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("status", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
