# Generated by Django 5.2.8 on 2025-11-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantinedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_path", models.CharField(max_length=500)),
                ("quarantine_path", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=200)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("restored", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("alert_type", models.CharField(max_length=100)),
                ("severity", models.CharField(default="medium", max_length=20)),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="core.connection",
                    ),
                ),
            ],
        ),
    ]
