# Generated by Django 5.2.8 on 2025-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quarantinedfile_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                ("ports", models.CharField(max_length=255)),
                ("open_ports", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
