# Generated by Django 5.2.8 on 2025-11-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_portscanlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500, unique=True)),
                ("recursive", models.BooleanField(default=True)),
                ("auto_quarantine", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
