# Generated by Django 5.2.8 on 2025-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_watchedfolder"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="src_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="src_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
