# Generated by Django 5.2.8 on 2025-11-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alert_src_city_alert_src_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
