# Generated by Django 5.2.8 on 2025-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alert_latitude_alert_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
