# Generated by Django 5.2.8 on 2025-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_appsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="src_ip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
