# Generated by Django 5.2.8 on 2025-11-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_malwaresignature_tlsh"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarantinedfile",
            name="fuzzy_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="quarantinedfile",
            name="match_distance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quarantinedfile",
            name="match_type",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="quarantinedfile",
            name="matched_signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quarantined_files",
                to="core.malwaresignature",
            ),
        ),
        migrations.AlterField(
            model_name="quarantinedfile",
            name="original_path",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="quarantinedfile",
            name="quarantine_path",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quarantinedfile",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
