# Generated by Django 5.2.6 on 2025-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_quarantinedfile_fuzzy_hash_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="connection",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="quarantinedfile",
            options={"ordering": ["-detected_at"]},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["timestamp"], name="core_alert_timesta_c680be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity"], name="core_alert_severit_81b97f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["alert_type"], name="core_alert_alert_t_0c2086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["src_ip"], name="core_alert_src_ip_3d5ce5_idx"),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["timestamp"], name="core_connec_timesta_ad0397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(fields=["src_ip"], name="core_connec_src_ip_b8f58d_idx"),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(fields=["dst_ip"], name="core_connec_dst_ip_346e06_idx"),
        ),
        migrations.AddIndex(
            model_name="quarantinedfile",
            index=models.Index(fields=["sha256"], name="core_quaran_sha256_a00240_idx"),
        ),
        migrations.AddIndex(
            model_name="quarantinedfile",
            index=models.Index(
                fields=["detected_at"], name="core_quaran_detecte_16fefb_idx"
            ),
        ),
    ]
