# Generated by Django 5.1.3 on 2025-11-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_alert_options_alter_connection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100, unique=True)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
            ],
        ),
    ]
