# Generated by Django 5.1.3 on 2025-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blockedip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortScanLog',
        ),
        migrations.AddField(
            model_name='alert',
            name='dst_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='dst_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='process_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='connection',
            name='pid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='ppid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='process_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
