# Generated by Django 6.0 on 2025-12-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_portscanlog_alert_dst_ip_alert_dst_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
