# Generated by Django 6.0 on 2025-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_alert_id_alter_appsetting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='dst_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='ip',
            field=models.GenericIPAddressField(unique=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='dst_ip',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='dst_port',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='src_ip',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='src_port',
            field=models.PositiveIntegerField(),
        ),
    ]
