# Generated by Django 6.0 on 2025-12-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_malwaresignature_ssdeep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarantinedfile',
            old_name='fuzzy_hash',
            new_name='tlsh',
        ),
    ]
