# Generated by Django 5.1.3 on 2025-12-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_fuzzy_hash_quarantinedfile_tlsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
