# Generated by Django 5.1.3 on 2025-12-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blockedip_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='ip',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
